/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatDemoClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatDemoPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Nothing,
 *   !proto.Messages>}
 */
const methodDescriptor_ChatDemo_GetMessages = new grpc.web.MethodDescriptor(
  '/ChatDemo/GetMessages',
  grpc.web.MethodType.UNARY,
  proto.Nothing,
  proto.Messages,
  /**
   * @param {!proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Messages.deserializeBinary
);


/**
 * @param {!proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Messages)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Messages>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatDemoClient.prototype.getMessages =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatDemo/GetMessages',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_GetMessages,
      callback);
};


/**
 * @param {!proto.Nothing} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Messages>}
 *     Promise that resolves to the response
 */
proto.ChatDemoPromiseClient.prototype.getMessages =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatDemo/GetMessages',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_GetMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Nothing,
 *   !proto.MessageEvent>}
 */
const methodDescriptor_ChatDemo_SubscribeMessageEvents = new grpc.web.MethodDescriptor(
  '/ChatDemo/SubscribeMessageEvents',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.Nothing,
  proto.MessageEvent,
  /**
   * @param {!proto.Nothing} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.MessageEvent.deserializeBinary
);


/**
 * @param {!proto.Nothing} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MessageEvent>}
 *     The XHR Node Readable Stream
 */
proto.ChatDemoClient.prototype.subscribeMessageEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatDemo/SubscribeMessageEvents',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_SubscribeMessageEvents);
};


/**
 * @param {!proto.Nothing} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.MessageEvent>}
 *     The XHR Node Readable Stream
 */
proto.ChatDemoPromiseClient.prototype.subscribeMessageEvents =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/ChatDemo/SubscribeMessageEvents',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_SubscribeMessageEvents);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.Message,
 *   !proto.Nothing>}
 */
const methodDescriptor_ChatDemo_NewMessage = new grpc.web.MethodDescriptor(
  '/ChatDemo/NewMessage',
  grpc.web.MethodType.UNARY,
  proto.Message,
  proto.Nothing,
  /**
   * @param {!proto.Message} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.Nothing.deserializeBinary
);


/**
 * @param {!proto.Message} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.Nothing)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.Nothing>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatDemoClient.prototype.newMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ChatDemo/NewMessage',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_NewMessage,
      callback);
};


/**
 * @param {!proto.Message} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.Nothing>}
 *     Promise that resolves to the response
 */
proto.ChatDemoPromiseClient.prototype.newMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ChatDemo/NewMessage',
      request,
      metadata || {},
      methodDescriptor_ChatDemo_NewMessage);
};


module.exports = proto;

